name: CI-integrity

on:
  push:
    branches:
      - main
      - major
      - minor
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

  pull_request:
    branches:
      - main
      - major
      - minor
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'package.json'
      - '*.lock'
      - '.yarnrc.yml'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Install Dependencies
        run: yarn --frozen-lockfile

      - name: Linter
        run: |
          yarn g:lint

      - name: typecheck
        run: |
          yarn g:typecheck

      - name: Unit tests
        run: |
          yarn workspaces foreach -At --exclude "@hyperse/hps-plugin-update" run test