name: ReleaseOrVersionPR

on:
  push:
    branches:
      - main
      

jobs:
  release:
    # Basic security: the release job can only be executed from this repo and from the main branch (not a remote thing)
    if: ${{ github.repository == 'hyperse-io/hps' && contains('refs/heads/main',github.ref)}}
    name: Release and changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # To run comparison we need more than the latest commit.
          # @link https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
          components: rustfmt, clippy

      - name: Verify Rust toolchain  
        run: |
          rustup show
          rustup toolchain list
          rustc --version
          cargo --version

      - name: Set Rust environment
        run: |
          echo "RUSTUP_HOME=$HOME/.rustup" >> $GITHUB_ENV
          echo "CARGO_HOME=$HOME/.cargo" >> $GITHUB_ENV
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Verify Rust before build
        run: |
          which cargo
          cargo --version
          rustup target list --installed
          rustup default stable
          rustup show

      - name: Build hps-srv-rspack-plugin-import
        working-directory: crates/hps-srv-rspack-plugin-import
        env:
          RUST_BACKTRACE: 1
          CARGO_TERM_COLOR: always
        run: |
          yarn clean
          yarn build

      # @link https://github.com/changesets/action
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn g:release
          cwd: ${{ github.workspace }}
          title: '[Release] Version packages'
          # Optional, might be used in conjunction with GITHUB_TOKEN to
          # allow running the workflows on a Version package action.
          # Be aware of security implications.
          # setupGitUser: true
        env:
          # See https://github.com/changesets/action/issues/147
          HOME: ${{ github.workspace }}
          # Allows to download / query / comment packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Allows to publish packages
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Support cargo
          CARGO_TERM_COLOR: always
          RUST_BACKTRACE: 1
